FROM postgres:16-alpine


# COPY ./docker/local/postgres/maintenance /usr/local/bin/maintenance

# RUN chmod =x /usr/local/bin/maintenance/*

# RUN mv /usr/local/bin/maintenance/* /usr/local/bin \
#   && mrdir /usr/local/bin/maintenance